// Code generated by "stringer -type ProfileKind"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProfUnused-0]
	_ = x[ProfReadInputFile-1]
	_ = x[ProfParsePairs-2]
	_ = x[ProfParsePair-3]
	_ = x[ProfParseNumber-4]
	_ = x[ProfParseFloat-5]
	_ = x[ProfCalculateDistances-6]
	_ = x[ProfReadReferenceFile-7]
	_ = x[ProfCompareReferenceFile-8]
	_ = x[ProfTotalRuntime-9]
	_ = x[ProfileCount-10]
}

const _ProfileKind_name = "ProfUnusedProfReadInputFileProfParsePairsProfParsePairProfParseNumberProfParseFloatProfCalculateDistancesProfReadReferenceFileProfCompareReferenceFileProfTotalRuntimeProfileCount"

var _ProfileKind_index = [...]uint8{0, 10, 27, 41, 54, 69, 83, 105, 126, 150, 166, 178}

func (i ProfileKind) String() string {
	if i < 0 || i >= ProfileKind(len(_ProfileKind_index)-1) {
		return "ProfileKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProfileKind_name[_ProfileKind_index[i]:_ProfileKind_index[i+1]]
}
