// Code generated by command: go run goasm_gen.go -out load.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Read_4x2_go(repeatCount uint64, bb []byte)
TEXT ·Read_4x2_go(SB), NOSPLIT, $0-32
	MOVQ repeatCount+0(FP), AX
	MOVQ bb_base+8(FP), CX

loop:
	MOVL (CX), BX
	MOVL 4(CX), BX
	ADDQ $0x08, DX
	CMPQ DX, AX
	JB   loop
	RET

// func Read_8x2_go(repeatCount uint64, bb []byte)
TEXT ·Read_8x2_go(SB), NOSPLIT, $0-32
	MOVQ repeatCount+0(FP), AX
	MOVQ bb_base+8(FP), CX

loop:
	MOVQ (CX), BX
	MOVQ 8(CX), BX
	ADDQ $0x10, DX
	CMPQ DX, AX
	JB   loop
	RET

// func Read_16x2_go(repeatCount uint64, bb []byte)
// Requires: AVX
TEXT ·Read_16x2_go(SB), NOSPLIT, $0-32
	MOVQ repeatCount+0(FP), AX
	MOVQ bb_base+8(FP), CX

loop:
	VMOVDQU (CX), X0
	VMOVDQU 16(CX), X1
	ADDQ    $0x20, DX
	CMPQ    DX, AX
	JB      loop
	RET

// func Read_32x2_go(repeatCount uint64, bb []byte)
// Requires: AVX
TEXT ·Read_32x2_go(SB), NOSPLIT, $0-32
	MOVQ repeatCount+0(FP), AX
	MOVQ bb_base+8(FP), CX

loop:
	VMOVDQU (CX), Y0
	VMOVDQU 32(CX), Y1
	ADDQ    $0x40, DX
	CMPQ    DX, AX
	JB      loop
	RET
