// Code generated by command: go run goasm_gen.go -out loops.s -stubs stub.go. DO NOT EDIT.

package goasm

func Read_4x2_go(repeatCount uint64, bb []byte)

func Read_8x2_go(repeatCount uint64, bb []byte)

func Read_16x2_go(repeatCount uint64, bb []byte)

func Read_32x2_go(repeatCount uint64, bb []byte)

func ReadSuccessiveSizes_go(repeatCount uint64, bb []byte, offsetMask uint64)

func ReadSuccessiveSizesNonPow2_go(repeatCount uint64, bb []byte, chunkSize uint64)

func ReadStrided_32x2_go(repeatCount uint64, bb []byte, chunkSize uint64, stride uint64)
